# Generated by Django 3.2.3 on 2021-05-27 08:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('user', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
                ('user', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10)])),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('be', models.FloatField()),
                ('tp1', models.FloatField()),
                ('tp2', models.FloatField()),
                ('tp3', models.FloatField()),
                ('comment', models.TextField(null=True)),
                ('user', models.IntegerField(null=True, unique=True)),
                ('position_index', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_all_app.index')),
                ('position_indicator', models.ManyToManyField(to='my_all_app.Indicator')),
            ],
        ),
    ]
