# Generated by Django 3.2.3 on 2021-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_all_app', '0002_auto_20210607_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
