# Generated by Django 3.2.3 on 2021-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_all_app', '0004_auto_20210705_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
