# Generated by Django 3.2.3 on 2021-07-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_all_app', '0005_alter_position_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_all_app.index'),
        ),
    ]
