# Generated by Django 3.2.3 on 2021-09-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_all_app', '0010_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
