# Generated by Django 3.2.3 on 2021-09-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_all_app', '0011_delete_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_index',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
